/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PlasticFactoryOutletTransportationRole;

import Business.Enterprise.Enterprise;
import Business.Organization.PlasticFactoryOutletTransportationOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.WorkQueue.PlasticFactoryOutletTransportationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.MessageFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranalinarkar
 */
public class PlasticFactoryOutletTransportationJPanel extends javax.swing.JPanel {
   private JPanel userProcessContainer;
    private PlasticFactoryOutletTransportationOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form PlasticFactoryOutletTransportationJPanel
     */
    public PlasticFactoryOutletTransportationJPanel(JPanel userProcessContainer, UserAccount userAccount, PlasticFactoryOutletTransportationOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        populateOutletComboBox();
        populateRequestTable();
    }

    
   private void populateOutletComboBox(){
     
     jOutlet.removeAllItems();
     jOutlet.addItem("OUTLET1");
     jOutlet.addItem("OUTLET2");
     jOutlet.addItem("OUTLET3");
     jOutlet.addItem("OUTLET4");
     jOutlet.addItem("OUTLET5");
     }
    
   
    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) jFOTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = request;
            
            row[2] = ((PlasticFactoryOutletTransportationWorkRequest) request).getNumberOfItemsProduced();
            
            row[1] = ((PlasticFactoryOutletTransportationWorkRequest) request).getSender();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFOTable = new javax.swing.JTable();
        jDelivered = new javax.swing.JButton();
        jOutlet = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jRefresh = new javax.swing.JButton();
        jDays = new javax.swing.JButton();
        jDaysTakenToComplete = new javax.swing.JTextField();
        jGenerateReport = new javax.swing.JButton();
        jSendReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Plastic Factory Outlet Transportation Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 34));

        jFOTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Quantity To be Delivered", "Distance(kms)", "Charges", "Name of Factory", "Status", "Delivery Date", "Delivery Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jFOTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 783, 90));

        jDelivered.setText("Delivered");
        jDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeliveredActionPerformed(evt);
            }
        });
        add(jDelivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jOutlet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel2.setText("Plastic OutletName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jRefresh.setText("Refresh");
        jRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshActionPerformed(evt);
            }
        });
        add(jRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jDays.setText("Days Taken To complete the cycle");
        jDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDaysActionPerformed(evt);
            }
        });
        add(jDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 356, -1, -1));

        jDaysTakenToComplete.setEditable(false);
        add(jDaysTakenToComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 353, 60, 30));

        jGenerateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reportsicon.png"))); // NOI18N
        jGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateReportActionPerformed(evt);
            }
        });
        add(jGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 305, 84, 67));

        jSendReport.setText("Send Report");
        jSendReport.setEnabled(false);
        jSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendReportActionPerformed(evt);
            }
        });
        add(jSendReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 398, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeliveredActionPerformed
        int selectedRow = jFOTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        PlasticFactoryOutletTransportationWorkRequest gcwr = (PlasticFactoryOutletTransportationWorkRequest) jFOTable.getValueAt(selectedRow, 0);
        if(gcwr.getMessage().equalsIgnoreCase("Delivered To Outlet")){
            JOptionPane.showMessageDialog(null, "Already Assigned");
            return;

        }
        String o= (String) jOutlet.getSelectedItem();
        if(o.equalsIgnoreCase("OUTLET1")){
            gcwr.setDistanceTravelled(20);
            gcwr.setMoneyEarnedInDelivering(30);
            gcwr.setNameOfOutlet(o);
            gcwr.setMessage("Delivered To Outlet");

        }
        if(o.equalsIgnoreCase("OUTLET2")){
            gcwr.setDistanceTravelled(10);
            gcwr.setMoneyEarnedInDelivering(20);
            gcwr.setNameOfOutlet(o);
            gcwr.setMessage("Delivered To Outlet");

        }
        if(o.equalsIgnoreCase("OUTLET3")){
            gcwr.setDistanceTravelled(30);
            gcwr.setMoneyEarnedInDelivering(40);
            gcwr.setNameOfOutlet(o);
            gcwr.setMessage("Delivered To Outlet");
        }
        if(o.equalsIgnoreCase("OUTLET4")){
            gcwr.setDistanceTravelled(40);
            gcwr.setMoneyEarnedInDelivering(60);
            gcwr.setNameOfOutlet(o);
            gcwr.setMessage("Delivered To Outlet");
        }
        if(o.equalsIgnoreCase("OUTLET5")){
            gcwr.setDistanceTravelled(50);
            gcwr.setMoneyEarnedInDelivering(80);
            gcwr.setNameOfOutlet(o);
            gcwr.setMessage("Delivered To Outlet");
        }
        JOptionPane.showMessageDialog(null, "Assigned");
        gcwr.setStatus("Delivery Completed");

        Date d=gcwr.getRequestDate();
        Date d1=gcwr.getFresolveDate();
        System.out.println(d);
        System.out.println(d1);
        long daystodeliver=(int)(d1.getTime()-d.getTime())/1000 % 60;
        System.out.println(daystodeliver);
        gcwr.setDaysTakenToComplete((int) daystodeliver);
        if(daystodeliver>0&&daystodeliver<45){

            gcwr.setResult("Delivered on time");
        }
        else
        {
            gcwr.setResult("Not Delivered on time");
        }
        
    }//GEN-LAST:event_jDeliveredActionPerformed

    private void jRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshActionPerformed

        DefaultTableModel model = (DefaultTableModel) jFOTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[9];
            row[0] = request;

            row[2] = ((PlasticFactoryOutletTransportationWorkRequest) request).getNumberOfItemsProduced();

            row[1] = ((PlasticFactoryOutletTransportationWorkRequest) request).getSender();
            row[3]=  ((PlasticFactoryOutletTransportationWorkRequest) request).getDistanceTravelled();
            row[4]=  ((PlasticFactoryOutletTransportationWorkRequest) request).getMoneyEarnedInDelivering();
            row[5]=  ((PlasticFactoryOutletTransportationWorkRequest) request).getNameOfOutlet();
            row[6]=  ((PlasticFactoryOutletTransportationWorkRequest) request).getStatus();
            row[7]=  ((PlasticFactoryOutletTransportationWorkRequest) request).getFresolveDate();
            row[8]=  ((PlasticFactoryOutletTransportationWorkRequest) request).getResult();

            model.addRow(row);
        }

    }//GEN-LAST:event_jRefreshActionPerformed

    private void jDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDaysActionPerformed

        int selectedRow = jFOTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        PlasticFactoryOutletTransportationWorkRequest gcwr = (PlasticFactoryOutletTransportationWorkRequest) jFOTable.getValueAt(selectedRow, 0);
        jDaysTakenToComplete.setText(String.valueOf(gcwr.getDaysTakenToComplete()));
    }//GEN-LAST:event_jDaysActionPerformed

    private void jGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateReportActionPerformed
        MessageFormat header=new MessageFormat("Report");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");

        try{

            jFOTable.print(JTable.PrintMode.NORMAL, header, footer);

        } catch(java.awt.print.PrinterException e){

            System.err.format("Cannot print %s%n",e.getMessage());

        }
        jSendReport.setEnabled(true);
        jGenerateReport.setEnabled(false);
    }//GEN-LAST:event_jGenerateReportActionPerformed

    private void jSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendReportActionPerformed
        SendEmailP manageOrganizationJPanel = new SendEmailP(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        jSendReport.setEnabled(false);
        jGenerateReport.setEnabled(true);
    }//GEN-LAST:event_jSendReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDays;
    private javax.swing.JTextField jDaysTakenToComplete;
    private javax.swing.JButton jDelivered;
    private javax.swing.JTable jFOTable;
    private javax.swing.JButton jGenerateReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jOutlet;
    private javax.swing.JButton jRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSendReport;
    // End of variables declaration//GEN-END:variables
}
