/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GarbageInDusbin;
import sun.audio.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GarbageManagerWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.*;
import java.net.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author pranalinarkar
 */
public class NotificationSentToManager extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Role role;
    private Enterprise enterprise;
    private Organization organization;

    //private GarbageCollectionManagerOrganization gcmo;

    /**
     * Creates new form NotificationSentToManager
     */
    public NotificationSentToManager(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
       // System.out.println(system.getName());

        populateAreaComboBox();
        populateComboBox();
//        populateType();

    }

    private void populateAreaComboBox() {

        jAreaCombo.removeAllItems();
        jAreaCombo.addItem("02120");
        jAreaCombo.addItem("02121");
        jAreaCombo.addItem("02122");
        jAreaCombo.addItem("02123");
        jAreaCombo.addItem("02124");
        jAreaCombo.addItem("02125");
        jAreaCombo.addItem("02126");
        jAreaCombo.addItem("02127");
        jAreaCombo.addItem("02128");
        jAreaCombo.addItem("02129");
        jAreaCombo.addItem("02130");
        jAreaCombo.addItem("02131");

    }
//  private void populateType(){
//  jType.removeAllItems();
//  jType.addItem("Normal");
//  jType.addItem("Suspected Item");
//  
//  }
    private void populateComboBox() {
        jNetworkCombo.removeAllItems();
        for (Network network : system.getNetworkList()) {
            jNetworkCombo.addItem(network);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jNetworkCombo = new javax.swing.JComboBox();
        jEnterpriseCombo = new javax.swing.JComboBox();
        jOrganization = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jManager = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jNotification = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMetal = new javax.swing.JTextField();
        jPlastic = new javax.swing.JTextField();
        jDegradable = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jAreaCombo = new javax.swing.JComboBox();
        jNormal = new javax.swing.JRadioButton();
        jSuspected = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 204));

        jNetworkCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jNetworkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNetworkComboActionPerformed(evt);
            }
        });

        jEnterpriseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jEnterpriseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnterpriseComboActionPerformed(evt);
            }
        });

        jOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrganizationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Notification Of Dustbin being Full");

        jLabel2.setText("Network");

        jLabel3.setText("Enterprise");

        jLabel4.setText("Organization");

        jManager.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManagerActionPerformed(evt);
            }
        });

        jLabel5.setText("Manager");

        jNotification.setText("Notification ");
        jNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotificationActionPerformed(evt);
            }
        });

        jLabel6.setText("Type of Garbage");

        jMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMetalActionPerformed(evt);
            }
        });

        jPlastic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlasticActionPerformed(evt);
            }
        });

        jLabel7.setText("Metal");

        jLabel8.setText("Plastic");

        jLabel9.setText("Degradable");

        jLabel10.setText("Area");

        jAreaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(jNormal);
        jNormal.setText("Normal");
        jNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jSuspected);
        jSuspected.setText("Suspected");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dustbinIcon.jpg"))); // NOI18N

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jNetworkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jEnterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jManager, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel4)
                                        .addGap(129, 129, 129)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel7)
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel8)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(jPlastic, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jDegradable, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(jAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(jNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(jSuspected))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOrganization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jManager)
                    .addComponent(jNetworkCombo)
                    .addComponent(jEnterpriseCombo))
                .addGap(27, 27, 27)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPlastic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDegradable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSuspected, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(backJButton)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManagerActionPerformed
//       jManager.removeAllItems();
//        Organization organization=(Organization)jOrganization.getSelectedItem();
//       
//        for (Employee emp: organization.getEmployeeDirectory().getEmployeeList()){
//                jManager.addItem(emp);
//        }
    }//GEN-LAST:event_jManagerActionPerformed

    private void jNetworkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNetworkComboActionPerformed
        // TODO add your handling code here:

        Network network1 = (Network) jNetworkCombo.getSelectedItem();

        if (network1 != null) {

            jEnterpriseCombo.removeAllItems();

            for (Enterprise enterprise : network1.getEnterpriseDirectory().getEnterpriseList()) {

                jEnterpriseCombo.addItem(enterprise);
            }
        }

    }//GEN-LAST:event_jNetworkComboActionPerformed

    private void jEnterpriseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnterpriseComboActionPerformed
        Enterprise enterprise1 = (Enterprise) jEnterpriseCombo.getSelectedItem();
        if (enterprise1 != null) {

            jOrganization.removeAllItems();

            for (Organization organization : enterprise1.getOrganizationDirectory().getOrganizationList()) {
                
                if(organization.getName().equalsIgnoreCase("GCManager Organization"))
                jOrganization.addItem(organization);
            }
        }


    }//GEN-LAST:event_jEnterpriseComboActionPerformed

    private void jOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrganizationActionPerformed
        Organization org = (Organization) jOrganization.getSelectedItem();

        if (org != null) {
            jManager.removeAllItems();
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                jManager.addItem(ua);
            }
        }
    }//GEN-LAST:event_jOrganizationActionPerformed

    private void jNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotificationActionPerformed
         
         
     
         
        
         
         
         
         
         
         
         
         
         
         
         
         
         
        
        GarbageManagerWorkRequest wk = new GarbageManagerWorkRequest();
         String area = (String) jAreaCombo.getSelectedItem();

        wk.setArea(area);
        if (jMetal.getText().equals("")) {
            wk.setMetalGarbageStatus("No Metal");
        } else {
            wk.setMetalGarbageStatus(jMetal.getText());

        }

        if (jPlastic.getText().equals("")) {
            wk.setPlasticStatus("No Plastic");
        } else {
            wk.setPlasticStatus(jPlastic.getText());

        }

        if (jDegradable.getText().equals("")) {
            wk.setBiodegradableStatus("No BioGarbage");
        } else {
            wk.setBiodegradableStatus(jDegradable.getText());

        }
        if(jMetal.getText().equals("")&&jPlastic.getText().equals("")&&jDegradable.getText().equals("")){
        JOptionPane.showMessageDialog(null, "NoGarbage in the Dustbin");
        return;
        }
        String type;
        if(jNormal.isSelected()){
        type="Normal";
        
        }
        else if(jSuspected.isSelected()){
        type="Suspected Item";
       
        }
        else{
        JOptionPane.showMessageDialog(null, "Select the type");
        return;
        
        }
        
       wk.setMessage("New Garbage");
       wk.setStatus("Please Empty the Dustbin");
       wk.setType(type);
        

        
        Organization og= (Organization) jOrganization.getSelectedItem();
        
        

        
        UserAccount ua = (UserAccount) jManager.getSelectedItem();
          wk.setReceiver(ua);
          
           
        
        JOptionPane.showMessageDialog(null, "Notification Sent to Manager");

        ua.getWorkQueue().getWorkRequestList().add(wk);
         og.getWorkQueue().getWorkRequestList().add(wk);
        JOptionPane.showMessageDialog(null, "Work request added.");
         
       

    }//GEN-LAST:event_jNotificationActionPerformed

    private void jPlasticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlasticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlasticActionPerformed

    private void jMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMetalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMetalActionPerformed

    private void jNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNormalActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    
    public static void sendMessage(String receiver,String message) {
        try {
            // Construct data
            String data = "";
            /*
             * Note the suggested encoding for certain parameters, notably
             * the username, password and especially the message.  ISO-8859-1
             * is essentially the character set that we use for message bodies,
             * with a few exceptions for e.g. Greek characters.  For a full list,
             * see:  http://bulksms.vsms.net/docs/eapi/submission/character_encoding/
             */
            data += "username=" + URLEncoder.encode("pranalin", "ISO-8859-1");
            data += "&password=" + URLEncoder.encode("Rockon@123", "ISO-8859-1");
            data += "&message=" + URLEncoder.encode(message, "ISO-8859-1");
            data += "&want_report=1";
            data += "&msisdn="+receiver;

            // Send data
            URL url = new URL("http://usa.bulksms.com:80/eapi/submission/send_sms/2/2.0?");
            /*
            * If your firewall blocks access to port 5567, you can fall back to port 80:
            * URL url = new URL("http://bulksms.vsms.net/eapi/submission/send_sms/2/2.0");
            * (See FAQ for more details.)
            */

            URLConnection conn = url.openConnection();
            conn.setDoOutput(true);
            OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());
            wr.write(data);
            wr.flush();

            // Get the response
            BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String line;
            while ((line = rd.readLine()) != null) {
                // Print the response output...
                System.out.println(line);
            }
            wr.close();
            rd.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    
    
//    public static void music(){
//    AudioPlayer MGP=AudioPlayer.player;
//    AudioStream BGM;
//    AudioData MD;
//     ContinuousAudioDataStream loop=null;
//     try{
//         BGM=new AudioStream(new FileInputStream("female-new-mail.mp3"));   
//    MD= BGM.getData();
//    loop= new ContinuousAudioDataStream(MD);
//     }
//     catch(IOException error){}
//         MGP.start(loop);
//
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jAreaCombo;
    private javax.swing.JTextField jDegradable;
    private javax.swing.JComboBox jEnterpriseCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jManager;
    private javax.swing.JTextField jMetal;
    private javax.swing.JComboBox jNetworkCombo;
    private javax.swing.JRadioButton jNormal;
    private javax.swing.JButton jNotification;
    private javax.swing.JComboBox jOrganization;
    private javax.swing.JTextField jPlastic;
    private javax.swing.JRadioButton jSuspected;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
