/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PlasticTransportationServiceRole;

import Business.Enterprise.Enterprise;

import Business.Organization.Organization;
import Business.Organization.PlasticRecyclingOrganization;
import Business.Organization.PlasticTransportationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PlasticRecyclingWorkRequest;
import Business.WorkQueue.PlasticTransportationWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranalinarkar
 */
public class PlasticTransportationJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private PlasticTransportationOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form PlasticTransportationJPanel
     */
    public PlasticTransportationJPanel(JPanel userProcessContainer, UserAccount userAccount, PlasticTransportationOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        populateRequestTable();
        populatePlasticRecycler();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPlasticTransortation = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPlasticRecycling = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jRefresh = new javax.swing.JButton();
        jSent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlasticTransortation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Plastic Transported(Kgs)", "Sender", "Receiver", "Charges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jPlasticTransortation);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 586, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Plastic Transportation WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 300, 25));

        jPlasticRecycling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jPlasticRecycling, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel2.setText("Plastic Recycler");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jRefresh.setText("Refresh");
        jRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshActionPerformed(evt);
            }
        });
        add(jRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jSent.setText("Sent");
        jSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSentActionPerformed(evt);
            }
        });
        add(jSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transportationicon.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshActionPerformed
        DefaultTableModel model = (DefaultTableModel) jPlasticTransortation.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = request;
           
            row[1] = ((PlasticTransportationWorkRequest) request).getSegregatedPlastic();
           
            row[2] = ((PlasticTransportationWorkRequest) request).getReceiver();
            
            row[3] = ((PlasticTransportationWorkRequest) request).getSentToPD();
            
            row[4] = ((PlasticTransportationWorkRequest) request).getMoneyEarned();

            model.addRow(row);
        }    
    }//GEN-LAST:event_jRefreshActionPerformed

    private void jSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSentActionPerformed
        int selectedRow = jPlasticTransortation.getSelectedRow();
         if(selectedRow<0){JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        UserAccount ua = (UserAccount) jPlasticRecycling.getSelectedItem();
        PlasticTransportationWorkRequest gcwr = (PlasticTransportationWorkRequest) jPlasticTransortation.getValueAt(selectedRow, 0);
        if(gcwr.getMessage().equalsIgnoreCase("Sent To Recycling")){
        JOptionPane.showMessageDialog(null, "Already Assigned");
            return;
        
        }
        
        String Message="Sent To Recycling";
        gcwr.setMessage(Message);
        gcwr.setSentToPD(ua);
        int dis= gcwr.getDistanceTravelled();
        int moneyPerKm=1;
        int total= dis*moneyPerKm;
        gcwr.setMoneyEarned(total);
        gcwr.setDistanceTravelled(dis);
        
        System.out.println(gcwr.getReceiver());
        PlasticRecyclingWorkRequest mrwk = new PlasticRecyclingWorkRequest();
        mrwk.setMessage("New recycling Batch");
        mrwk.setSegregatedPlastic(gcwr.getSegregatedPlastic());
        mrwk.setSender(mrwk.getReceiver());
        mrwk.setReceiver(ua);
        mrwk.setRequestDate(gcwr.getRequestDate());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PlasticRecyclingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){

            ua.getWorkQueue().getWorkRequestList().add(mrwk);

            JOptionPane.showMessageDialog(null,"Work request added.");
        }
    }//GEN-LAST:event_jSentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jPlasticRecycling;
    private javax.swing.JTable jPlasticTransortation;
    private javax.swing.JButton jRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSent;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {
DefaultTableModel model = (DefaultTableModel) jPlasticTransortation.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
           
            row[1] = ((PlasticTransportationWorkRequest) request).getSegregatedPlastic();
           
            row[2] = ((PlasticTransportationWorkRequest) request).getReceiver();
            
            row[3] = ((PlasticTransportationWorkRequest) request).getSentToPD();
            

            model.addRow(row);
        }    }
    
    
    
    public void populatePlasticRecycler() {

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof PlasticRecyclingOrganization) {

                org = organization;
                break;
            }
        }
        if (org != null) {
            jPlasticRecycling.removeAllItems();
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                jPlasticRecycling.addItem(ua);
            }
        }
    }
}
