/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BioTransportationRole;

import Business.Enterprise.Enterprise;
import Business.Organization.BioRecyclingOrganization;
import Business.Organization.BioTransportationOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BioRecyclingWorkRequest;
import Business.WorkQueue.BioTransportationWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranalinarkar
 */
public class BioTransportationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BioTransportationJPanel
     */
   
     private JPanel userProcessContainer;
    private BioTransportationOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public BioTransportationJPanel(JPanel userProcessContainer, UserAccount userAccount, BioTransportationOrganization organization, Enterprise enterprise) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
         populateRequestTable(); 
         populateBioRecycler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jBioDegradableTransortation = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBioRecycling = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jRefresh = new javax.swing.JButton();
        jSent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBioDegradableTransortation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "BioDegradable Transported(Kgs)", "Sender", "Receiver", "Charges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jBioDegradableTransortation);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 586, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BioDegradable Transportation WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 20, 382, 25));

        jBioRecycling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jBioRecycling, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel2.setText("BioDegradable Recycler");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jRefresh.setText("Refresh");
        jRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshActionPerformed(evt);
            }
        });
        add(jRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jSent.setText("Sent");
        jSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSentActionPerformed(evt);
            }
        });
        add(jSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transportationicon.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshActionPerformed
       DefaultTableModel model = (DefaultTableModel) jBioDegradableTransortation.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = request;
           
            row[1] = ((BioTransportationWorkRequest) request).getSegregatedDegradable();
           
            row[2] = ((BioTransportationWorkRequest) request).getReceiver();
            
            row[3] = ((BioTransportationWorkRequest) request).getSentToBD();
            
            row[4] = ((BioTransportationWorkRequest) request).getMoneyEarned();

            model.addRow(row);
        }    
    }//GEN-LAST:event_jRefreshActionPerformed
       
     public void populateBioRecycler() {

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof BioRecyclingOrganization) {

                org = organization;
                break;
            }
        }
        if (org != null) {
            jBioRecycling.removeAllItems();
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                jBioRecycling.addItem(ua);
            }
        }
    }
    private void populateRequestTable() {
    DefaultTableModel model = (DefaultTableModel) jBioDegradableTransortation.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
           
            row[1] = ((BioTransportationWorkRequest) request).getSegregatedDegradable();
           
            row[2] = ((BioTransportationWorkRequest) request).getReceiver();
            
            row[3] = ((BioTransportationWorkRequest) request).getSentToBD();
            

            model.addRow(row);
        }    }
    
    
    
    private void jSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSentActionPerformed
        int selectedRow = jBioDegradableTransortation.getSelectedRow();
         if(selectedRow<0){JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        UserAccount ua = (UserAccount) jBioRecycling.getSelectedItem();
        BioTransportationWorkRequest gcwr = (BioTransportationWorkRequest) jBioDegradableTransortation.getValueAt(selectedRow, 0);
        if(gcwr.getMessage().equalsIgnoreCase("Sent To Recycling")){
        JOptionPane.showMessageDialog(null, "Already Assigned");
            return;
        
        }
        String Message="Sent To Recycling";
        gcwr.setMessage(Message);
        gcwr.setSentToBD(ua);
        int dis= gcwr.getDistanceTravelled();
        int moneyPerKm=1;
        int total= dis*moneyPerKm;
        gcwr.setMoneyEarned(total);
        gcwr.setDistanceTravelled(dis);
        
        BioRecyclingWorkRequest mrwk = new BioRecyclingWorkRequest();
        mrwk.setMessage("New recycling Batch");
        mrwk.setSegregatedDegradable(gcwr.getSegregatedDegradable());
        mrwk.setSender(mrwk.getReceiver());
        mrwk.setReceiver(ua);
         mrwk.setRequestDate(gcwr.getRequestDate());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BioRecyclingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){

            ua.getWorkQueue().getWorkRequestList().add(mrwk);

            JOptionPane.showMessageDialog(null,"Work request added.");
        }
    }//GEN-LAST:event_jSentActionPerformed
                        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jBioDegradableTransortation;
    private javax.swing.JComboBox jBioRecycling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSent;
    // End of variables declaration//GEN-END:variables
}
